version: '3.4'

x-common-variables: &common-variables
 # CELERY_BROKER_URL: redis://redis:6379
 # CELERY_RESULT_BACKEND: redis://redis:6379
 # MINIO_ACCESS_KEY: minio
 # MINIO_SECRET_KEY: minio123
 # MINIO_URL: minio:9000
 # MINIO_BUCKET_NAME: hse-api-bucket
 # MYSQL_HOST: mysql
 # MYSQL_ROOT_PASSWORD: mysql123
 # MYSQL_USER: mysql
 # MYSQL_PASSWORD: mysql123
 # MYSQL_DATABASE: hse-api-database
  RESTRICTED_MODE: 0

services:

  splitter-web:
    build: .
    ports:
     - "80:80"
    tty: true
    networks:
     - default
    environment: *common-variables
